### ISSUE TITLE
Create Save Dialog Box For LEX Files

### ISSUE THREAD

**Issue by alexmgrau** [SpliceVR/SpliceVREditor#6]
Create a dialog box that allows you to set the location and name for the LEX file. After a quick google search, this does not seem to be a straight forward javascript call. May require a custom solution.

**Comment by caseyh** [comment]
https://github.com/eligrey/FileSaver.js/
Like this kind of thing? I'm not sure if there is anything better. Auto saving would be nice down the line, but not sure it's feasible on the client side only.

**Comment by grobm** [comment]
The Save Dialog function will really depend on were you are planning to write your output. This really will become a write permission question, javascript has many methods to write a file.

**Comment by alexmgrau** [comment]
Yeah, we can already write to a file but it just automatically downloads a file to the Downloads folder and doesn't let you set the name or location.

Casey, I think FileSaver.js a good option for now. If we include a text box at the top left of the screen near the add button, people can change the name of the project and then save it. It will then download as that file name. Same goes when importing a project.

As for auto-saving, we can definitely autosave on the server and/or in a temp directory on the client side. 

Not sure why this made me think of this but it will also be important to have Undo/Redo, although it won't make sense to add until we have a more solid structure for the editor.
